### ISSUE TITLE
how can i prepare dataset when using classifier.py

### ISSUE THREAD

**Issue by thomasgds** [nayeem8527/Live-Facial-Recognition#1]
I meet some problem when i use classifier.py to train new dataset, as below:
"
Number of classes: 1
Number of images: 30
labels:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

error:
Training classifier
Traceback (most recent call last):
  File "classifier.py", line 176, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "classifier.py", line 102, in main
    model.fit(emb_array, labels)
  File "/home/yview/.local/lib/python2.7/site-packages/sklearn/svm/base.py", line 150, in fit
    y = self._validate_targets(y)
  File "/home/yview/.local/lib/python2.7/site-packages/sklearn/svm/base.py", line 525, in _validate_targets
    " class" % len(cls))
ValueError: The number of classes has to be greater than one; got 1 class
"

The new dataset locate at the same dir as:
    ./dataset
        |__ thomas
                |__thomas_0001.jpg
                |__thomas_0002.jpg
                ...
                |__thomas_00030.jpg
The command as below:
    python classifier.py --image_size 160 --batch_size 30 TRAIN dataset models/20170511-185253.pb thomas

i think classifier.py can not read the labels from the dataset.
how can i do to make classifier.py read the labels correctly?

**Comment by nayeem8527** [comment]
Hi Thomas, 

You need to use the train_classifier.py file as I have mentioner in the readme. And also please prefer to give only jpg images for now in the training data and also atleast 2 classes with minimum 5 images per class for training. 
I have debugged the code for taking the dataset, so please take a pull before running the code.
