### ISSUE TITLE
GPU to get 17fps

### ISSUE THREAD

**Issue by skyap** [nayeem8527/Live-Facial-Recognition#3]
hi, may i know your computer specification to get 17fps?

**Comment by nayeem8527** [comment]
Hello,
My computer spec is:
i7 -- 6 cores cpu
16gb ram
6gb nvidia gtx 1060

Be sure that 17fps goes for only detection also when there is only single face, for doing real time recognition, fps will go down significantly.
The current implementation is not that optimized to give good fps.
Soon the code will be updated to give higher fps and more accurate result.

**Comment by skyap** [comment]
thanks!
